name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 4.7.0
  build_resolvers: 2.0.9
  dart_style: 2.2.3
  sqflite: 2.0.2+1

dependencies:
  async: 2.9.0
  dartx: 1.0.0
  decimal: 2.1.0
  device_info_plus: 3.2.3
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.0
  injectable: 1.5.3
  intl: 0.17.0
  mime: 1.0.1
  package_info_plus: 1.3.0
  path_provider: 2.0.7
  rxdart: 0.26.0
  timezone: 0.8.0
  url_launcher: 6.0.17

dev_dependencies:
  build_runner: 2.1.7
  dart_code_metrics: 4.17.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.1.1
  freezed_annotation: 2.1.0
  injectable_generator: 1.5.3
  mocktail: 0.3.0
